In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from scipy import stats

In [2]:
hours = [0.50, 0.75, 1.00, 1.25, 1.50, 1.75, 1.75, 2.00, 2.25, 2.50, 2.75, 3.00, 3.25, 3.50, 4.00, 4.25, 4.50, 4.75, 5.00, 5.50]
# 0 no pass, 1 yes pass
target = [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1]

In [3]:
hours

[0.5,
 0.75,
 1.0,
 1.25,
 1.5,
 1.75,
 1.75,
 2.0,
 2.25,
 2.5,
 2.75,
 3.0,
 3.25,
 3.5,
 4.0,
 4.25,
 4.5,
 4.75,
 5.0,
 5.5]

In [4]:
target 

[0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1]

In [5]:
data = pd.DataFrame({
    'hours' : hours,
    'target' : target
})

In [6]:
data

hours  target
0    0.50       0
1    0.75       0
2    1.00       0
3    1.25       0
4    1.50       0
5    1.75       0
6    1.75       1
7    2.00       0
8    2.25       1
9    2.50       0
10   2.75       1
11   3.00       0
12   3.25       1
13   3.50       0
14   4.00       1
15   4.25       1
16   4.50       1
17   4.75       1
18   5.00       1
19   5.50       1

In [7]:
y = data.target
X = data.drop('target', axis=1)

In [8]:
logreg = LogisticRegression(random_state=42, C=1e9)

In [9]:
logreg.fit(X, y)

LogisticRegression(C=1000000000.0, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [10]:
logreg.coef_

array([[1.50464522]])

In [11]:
logreg.intercept_

array([-4.07771764])

In [90]:
def logit_pvalue(model, x):
    """ Calculate z-scores for scikit-learn LogisticRegression.
    parameters:
        model: fitted sklearn.linear_model.LogisticRegression with intercept and large C
        x:     matrix on which the model was fit
    This function uses asymtptics for maximum likelihood estimates.
    """
    p = model.predict_proba(x)
    n = len(p)
    m = len(model.coef_[0]) + 1
    coefs = np.concatenate([model.intercept_, model.coef_[0]])
    x_full = np.matrix(np.insert(np.array(x), 0, 1, axis = 1))
    ans = np.zeros((m, m))
    for i in range(n):
        ans = ans + np.dot(np.transpose(x_full[i, :]), x_full[i, :]) * p[i,1] * p[i, 0]
    vcov = np.linalg.inv(np.matrix(ans))
    se = np.sqrt(np.diag(vcov))
    t =  coefs/se  
    p = (1 - stats.norm.cdf(abs(t))) * 2
    return p

In [94]:
logit_pvalue(logreg, X.reshape(-1, 1))

array([0.02058146, 0.01670279])

In [100]:
X

array([0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 1.75, 2.  , 2.25, 2.5 , 2.75,
       3.  , 3.25, 3.5 , 4.  , 4.25, 4.5 , 4.75, 5.  , 5.5 ])

In [103]:
sm_model = sm.Logit(data.target, sm.add_constant(data.hours)).fit(disp=0)


In [107]:
print(sm_model.pvalues)

const    0.020582
hours    0.016703
dtype: float64


In [108]:
sm_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                 target   No. Observations:                   20
Model:                          Logit   Df Residuals:                       18
Method:                           MLE   Df Model:                            1
Date:                Tue, 28 Jan 2020   Pseudo R-squ.:                  0.4208
Time:                        21:39:33   Log-Likelihood:                -8.0299
converged:                       True   LL-Null:                       -13.863
Covariance Type:            nonrobust   LLR p-value:                 0.0006365
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -4.0777      1.761     -2.316      0.021      -7.529      -0.626
hours          1.5046      0.629      2.393      0.017       0.272       2.737
==============================================================================
"""