In [152]:
import pandas as pd
import numpy as np

In [153]:
numbers = np.array([6, 1, 2, 3, 4, 5])

ascending = numbers.copy()
ascending = ascending / 5
ascending.sort()

reverse = numbers.copy()
reverse = reverse / 2
reverse.sort()

data = pd.DataFrame({'a' : ascending,
                     'b' : reverse,
                     'c' : numbers})

In [154]:
data

a    b  c
0  0.2  0.5  6
1  0.4  1.0  1
2  0.6  1.5  2
3  0.8  2.0  3
4  1.0  2.5  4
5  1.2  3.0  5

In [155]:
def get_sum_of_columns(df):
    print('SUMS')
    for i in df.columns:
        result = df[i].values.sum()
        print(f'{i} : {result}')

In [156]:
def get_sum_of_rows(df):
    print('Sum of Rows')
    for i in range(df.shape[0]):
        row = np.array(df.iloc[i])
        result = round(row.sum(), 4)
        print(f'{i} : {result}')

In [157]:
def get_decending_indices(arr):
    indices = np.argsort(np.array(arr))[::-1]
    return indices

In [158]:
def apply_indexing(df, indices):
    result = df
    result = result.reindex(index=result.index.values[indices])
    result = result.reindex(index=result.index[::-1])
    return result

In [159]:
def comulative_dist(df):
    result = pd.DataFrame(columns=df.columns, index=df.index)
    
    for i in df.columns:
        column_sum = df[i].sum()
        norm_column = [] 

        for j in df[i]:
            res = round(j / column_sum, 4)
            norm_column.append(res)


        result[i] = norm_column
        
    return result

In [160]:
def norm_sum_of_methods(df):
    result = pd.DataFrame(columns=['norm_sum'], index=df.index)
    sum_of_rows = []
    
    for i in range(df.shape[0]):
        row = np.array(df.iloc[i])
        row_sum = np.sum(row)
        
        sum_of_rows.append(row_sum)
    
    result['norm_sum'] = sum_of_rows
    
    norm_result = comulative_dist(result)
    
    return norm_result
    

In [161]:
def norm_prod_of_methods(df):
    result = pd.DataFrame(columns=['norm_product'], index=df.index)
    norm_product = []
    
    for i in range(df.shape[0]):
        row = np.array(df.iloc[i])
        row_prod = np.prod(row)
        
        norm_product.append(row_prod)
        
    result['norm_product'] = norm_product
    # normalize result data frame
    norm_result = comulative_dist(result)
    
    return   norm_result

In [162]:
get_sum_of_columns(data)

SUMS
a : 4.2
b : 10.5
c : 21


In [163]:
norm_data = comulative_dist(data)
get_sum_of_columns(norm_data)

SUMS
a : 1.0
b : 1.0
c : 1.0


In [164]:
norm_data

a       b       c
0  0.0476  0.0476  0.2857
1  0.0952  0.0952  0.0476
2  0.1429  0.1429  0.0952
3  0.1905  0.1905  0.1429
4  0.2381  0.2381  0.1905
5  0.2857  0.2857  0.2381

In [165]:
norm_sum = norm_sum_of_methods(norm_data)

In [166]:
norm_sum.sum()

norm_sum    0.9999
dtype: float64

In [167]:
norm_prod = norm_prod_of_methods(norm_data)

In [168]:
norm_prod.sum()

norm_product    0.9999
dtype: float64

In [169]:
get_decending_indices(norm_sum['norm_sum'])

array([5, 4, 3, 2, 0, 1])

In [170]:
get_decending_indices(norm_prod['norm_product'])

array([5, 4, 3, 2, 0, 1])

In [171]:
norm_prod

norm_product
0        0.0168
1        0.0112
2        0.0506
3        0.1349
4        0.2809
5        0.5055

In [172]:
norm_prod = apply_indexing(norm_prod, get_decending_indices(norm_prod['norm_product']))

In [173]:
norm_prod

norm_product
1        0.0112
0        0.0168
2        0.0506
3        0.1349
4        0.2809
5        0.5055

In [174]:
norm_prod['norm_product'].values

array([0.0112, 0.0168, 0.0506, 0.1349, 0.2809, 0.5055])

In [175]:
norm_sum = apply_indexing(norm_sum, get_decending_indices(norm_sum['norm_sum']))

In [176]:
norm_sum

norm_sum
1    0.0793
0    0.1270
2    0.1270
3    0.1746
4    0.2222
5    0.2698

In [177]:
apply_indexing(norm_data, get_decending_indices(norm_sum['norm_sum']))

a       b       c
0  0.0476  0.0476  0.2857
1  0.0952  0.0952  0.0476
2  0.1429  0.1429  0.0952
3  0.1905  0.1905  0.1429
4  0.2381  0.2381  0.1905
5  0.2857  0.2857  0.2381

In [178]:
norm_data.reindex(index=norm_data.index.values[get_decending_indices(norm_sum['norm_sum'])])

a       b       c
5  0.2857  0.2857  0.2381
4  0.2381  0.2381  0.1905
3  0.1905  0.1905  0.1429
2  0.1429  0.1429  0.0952
1  0.0952  0.0952  0.0476
0  0.0476  0.0476  0.2857

In [179]:
norm_data

a       b       c
0  0.0476  0.0476  0.2857
1  0.0952  0.0952  0.0476
2  0.1429  0.1429  0.0952
3  0.1905  0.1905  0.1429
4  0.2381  0.2381  0.1905
5  0.2857  0.2857  0.2381